function getCategoryData() {

    return [
        {
            title: 'Skincare',
            description: 'Navigating the world of skincare can be extremely confusing, especially when you’re bombarded with numerous ingredient names (many of which sound very similar!). To help you decipher your hyaluronic from your glycolic and Vitamin A from your Vitamin C, we have put together a handy guide on some of the more well-known ingredients, so you can have a better idea of what will work best on for your skin. Chock full of antioxidants, phytochemicals and essential minerals, algae is a fantastic ingredient for revitalizing, hydrating, and toning skin. It also works to improve the skins elasticity, restore skin tone, and fight signs of ageing. There are many types of algae used in skincare, with the most common being red seaweed, green seaweed, brown kelp and spirulina. Aloe vera is often used to treat sunburn or rashes on the skin. It contains polysaccharides, which are known for their ability to hydrate the skin as well as bring down inflammation (so perfect for issues like irritation, itching and dryness). If you have sensitive skin, this is a good ingredient to look out for. Quick to absorb into the skin, argan oil is highly prized for its ability to moisturize without clogging pores. It works to reduce the appearance of fine lines and leave skin looking plumped and conditioned. Made from grains such as wheat and barley, azelaic acid is a common ingredient used topically to treat acne and rosacea, azelaic acid works to kill bacteria, reduce inflammation as well as treat hyperpigmentation.',
            descriptionLong: 'Great skin and animal-friendly formulations needn’t be at odds. Plant-based, sustainable ingredients make our range of vegan skincare and body products suitable for everyone to enjoy. Find everything from exclusive vegan and cruelty-free skin and body care ranges to be friendly soaps and natural hand wash and lotions. So what makes a skincare product vegan? Like vegan food, vegan skincare contains zero animal-derived ingredients or by-products. Non-vegan ingredients can include beeswax and honey and silk protein. Lesser-known ingredients that are non-vegan include biotin, acetyl alcohol, keratin, and gelatin, which are all frequently used in skincare (organizations like PETA have a full list of such ingredients on their website for you to cross-check that your beauty product doesn’t contain animal derivatives). Other non-vegan ingredients can include bee venom – which is sometimes used in products to numb the muscles in the face, for a ‘topical Botox’ effect; as well as lanolin – a wax secreted by sheep through their wool, and which is often a key ingredient in lip balm and moisturizer. Certain fragrances in skincare can also be non-vegan; ambergris is a highly prized perfume ingredient that adds a rich scent and is basically – wait for it – whale faces! If you don’t like the sound of all that, then a vegan skincare regime might be the answer. Not only is vegan skincare more eco-friendly (not to mention better for our four- and six-legged friends), but also vegan ingredients tend to be gentler on the skin, making them less likely to cause redness and irritation. What’s more, vegan formulas are good at calming sensitive skin as the formulas tend to be more alkaline, helping to relieve conditions like stress rashes and acne. If you’re on the lookout for vegan skincare, they are usually very easy to spot. Usually, the packaging has a ‘V’ logo. If it simply says ‘cruelty-free’ this doesn’t mean it is vegan. While a product may not have been tested on animals (thereby making it cruelty-free) it still might contain animal-derived ingredients, so they are not the same thing.',
            coverImg: 'https://images.pexels.com/photos/9496429/pexels-photo-9496429.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
        },
        {
            title: 'Fragrances',
            description: 'The way we use and enjoy fragrance has shifted; its no longer just a step in our beauty routine, but its part of the bigger picture of how we feel, shop, and embrace current trends and movements. The last few years have been a funny ol time for perfume, havent they? As we get ready to say hello to a new year, we are reflecting on the growing trends of 2021, plus the up-and-coming trends that will be joining them in the world of fragrance in 2022.  Expect to see all of this over the next 12 months. A signature scent isnt just about how it smells. A good perfume can boost your mood, calm you after a stressful day and even remind you of fond memories. In a year where we have grabbed anything ‘feel-good with both hands, were not surprised uplifting scents have reigned supreme! Are you looking for a staple feel-good scent to add to your line-up? Look for perfumes with notes of bergamot, jasmine, or ylang-ylang, or check out our favorites here: Top 10 feel-good fragrances.',
            descriptionLong: 'Has every room in your house started to feel a bit the same? Dont worry, youre not alone in that feeling! To help create some boundaries within the same four walls, we saw a new wellness trend emerge known as ‘fragrance-zoning’ or ‘scent-scaping’. It involves using different scents in different rooms to help compartmentalize your thoughts and daily activities. With sustainability being on our minds more than ever, it’s no surprise it is one of the hottest fragrance topics of the year. Aside from how a scent smells, recyclable packaging and how environmentally friendly a fragrance are both become significant factors in how someone chooses a new perfume. In light of this, more and more brands have been following in MUGLER’s footsteps when it comes to refillable bottles; look at Armani’s My Way or Lancôme’s Idôle to see how it’s done. Then there is the transparency of ingredients to think about, whether vegan or cruelty-free, and if the brand aligns with your values. It may feel a bit of a minefield right now, but at The Perfume Shop, were committed to helping you ‘Feel Good When You Smell Good. Just check our sustainability commitment and goals here: Our Planet.',
            coverImg: 'https://www.theperfumeshop.com/blog/wp-content/uploads/2019/12/alien-goddess.jpg',
        },
        {
            title: 'Makeup',
            description: 'Whether you’re a makeup artist in the making or you’ve got a cosmetic bag that’s full of products long past their prime, you’ve come to the right place. We’ve got the women’s makeup you need to give your stash an instant refresh. So, start scrolling to find your new favorites. So many of my clients ask me about my story. The story of how I got into Makeup Artistry and the places it’s taken me. I’ve learned in life that everybody has a story to tell. Whether grand or humble, we’ve all had experiences that have shaped us into the people we are today. So, without any fancy pictures, here is my story, straight from the heart. My story of why and how I became a Makeup Artist. Ever since being a little girl, I loved playing with makeup and styling hair. But then again, a lot of little girls did exactly the same too. I grew up playing ‘makeup artists’ with my friend, I was influenced heavily by the makeup that my favorite pop stars wore, and I subjected my mum to many hours of playing ‘hairdressers’ where she’d inevitably end up with high pigtails which I used to find particularly hilarious. One of my first makeup artistry books came with a copy of J17 (I believe it to be this magazine anyway), my favorite teeny bopper magazine after graduating from Mizz, and it was a Bobbi Brown makeup guide. I read the book from cover to cover many times over and tried to re-create the looks. I thought she was an absolute goddess. She knew so much about every skin type, which colors worked for who and exactly how I could enhance my fair, freckled skin. Bobbi still is a makeup goddess by the way. She’s still an inspiration and a very influential makeup artist that’s helped to shape the industry. Soon after my Bobbi Brown book, I was given a Body Shop beauty book and was even treated to a blush from the shop too.',
            descriptionLong: 'One of my first makeup artistry books came with a copy of J17 (I believe it to be this magazine anyway), my favorite teeny bopper magazine after graduating from Mizz, and it was a Bobbi Brown makeup guide. I read the book from cover to cover many times over and tried to re-create the looks. I thought she was an absolute goddess. She knew so much about every skin type, which colors worked for who and exactly how I could enhance my fair, freckled skin. Bobbi still is a makeup goddess by the way. She’s still an inspiration and a very influential makeup artist that’s helped to shape the industry. Soon after my Bobbi Brown book, I was given a Body Shop beauty book and was even treated to a blush from the shop too.',
            coverImg: 'https://images.pexels.com/photos/3018845/pexels-photo-3018845.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
        },
    ]

}

export default getCategoryData